Automate ca certificate generation.

diff --git a/microbenchmarks-async/rust/run b/microbenchmarks-async/rust/run
--- a/microbenchmarks-async/rust/run
+++ b/microbenchmarks-async/rust/run
@@ -13,6 +13,11 @@ generate_conf() {
         ./generate_conf_cop || exit 1
     fi
 
+    if [ ! -f ca-root/crt ]; then
+      echo "Missing ca certificates, generating them".
+      ./ca || exit 1
+    fi
+
     if [ ! -f config/clients.config ]; then
         echo Error: Missing config/clients.config! >&2
         exit 1
