finish benchmark script

diff --git a/microbenchmarks/benchmark b/microbenchmarks/benchmark
--- a/microbenchmarks/benchmark
+++ b/microbenchmarks/benchmark
@@ -18,6 +18,12 @@ bigcooldown() {
     sleep 60
 }
 
+cmd() {
+    cop=$1
+    shift
+    sudo -u tcarvalho ssh $cop -- $@
+}
+
 ################################################################################
 
 # config params
@@ -34,10 +40,9 @@ BATCHES="8 16 32 128 512 1024"
 CLIENTS="1 10 30 60 100 1000"
 RESULTS=results
 
-# generate_env <backend> <id> <num clients> <num replicas> <batch size>
+# generate_env <backend> <num clients> <num replicas> <batch size>
 generate_env() {
     cat << EOF
-export ID=$2
 export LOCAL=0
 
 export COMPILE=0
@@ -45,9 +50,9 @@ export BACKEND=$1
 export VERBOSE=false
 export UPDATE_MAX_FDS=1
 
-export NUM_CLIENTS=$3
-export NUM_REPLICAS=$4
-export BATCH_SIZE=$5
+export NUM_CLIENTS=$2
+export NUM_REPLICAS=$3
+export BATCH_SIZE=$4
 
 export OPS_NUMBER=$OPS_NUMBER
 export MEASUREMENT_INTERVAL=$MEASUREMENT_INTERVAL
@@ -61,9 +66,11 @@ EOF
 
 ################################################################################
 
-# run as root!
-if [ $(id -u) -ne 0 ]; then
-    echo Run this script as root!
+# abort execution if we are not orchestrating this benchmark
+# from the cop-gpu node, which will launch all replicas and
+# execute its clients
+if [ ${HOSTNAME%%\.*} != "cop-gpu" ]; then
+    echo Invalid host detected. Please run this script from cop-gpu.
     exit 1
 fi
 
@@ -72,6 +79,11 @@ cd "$(dirname $0)"
 
 # update git repo
 git pull
+
+if [ ! -d "rust/ca-root" ]; then
+    echo No CA root found. Please regenerate it.
+    exit 1
+fi
 
 # ask to continue
 echo "Run tests? This will purge any old results!"
@@ -95,127 +107,112 @@ done
 for i in `seq 1 4`; do
     cop=cop0${i}
     log Killing all replicas 'in' $cop
-    sudo ssh $cop "pkill -f microbenchmarks" >/dev/null 2>/dev/null &
-    sudo ssh $cop "pkill -f bft-smart" >/dev/null 2>/dev/null &
+    cmd $cop sudo pkill -f microbenchmarks >/dev/null 2>/dev/null &
+    cmd $cop sudo pkill -f bft-smart >/dev/null 2>/dev/null &
 done
 smallcooldown
 
-# rebuild software
-log Building Rust YCSB service
-for i in `seq 1 4`; do
-    cop=cop0${i}
-    sudo -u tcarvalho ssh $cop '. .cargo/env; cd tg; git pull; cd ycsb/service; env RUSTFLAGS="-C target-cpu=native" cargo build --release'
-    if [ $? -ne 0 ]; then
-        log Error: "Couldn't update service in $cop"
-        exit 1
-    fi
-done
-log Building Java YCSB client
-./gradlew shadowJar
-pkill -f java
-
-# wait for systems to recover
-bigcooldown
-
 # execute benchmarks
-log Beginning tests
 rm -rf $RESULTS # purge old results
 mkdir -p $RESULTS
-for no_replicas in $(echo $REPLICAS); do
-    log Init of benchmarking $no_replicas replicas
 
-    for batch_size in $(echo $BATCHES); do
-        log Init of testing a batch size of $batch_size
+log Beginning tests
+for backend in java rust; do
+    log Init of benchmarking backend $backend
 
-        for no_clients in $(echo $CLIENTS); do
-            log Init of benchmarking $no_clients clients
+    for no_replicas in $(echo $REPLICAS); do
+        log Init of benchmarking $no_replicas replicas
 
-            # run each test 3 times, each test runs for 5min
-            for run_no in `seq 0 2`; do
-                log Init of run no. $run_no
+        for batch_size in $(echo $BATCHES); do
+            log Init of testing a batch size of $batch_size
 
-                targetdir="${RESULTS}/r=${no_replicas}/b=${batch_size}/c=${no_clients}/run=${run_no}"
-                start=${targetdir}/start
-                end=${targetdir}/end
+            for no_clients in $(echo $CLIENTS); do
+                log Init of benchmarking $no_clients clients
 
-                mkdir -p $targetdir
-                date +%s > $start
+                # generate environment files
+                log Generating 'local' environment file
+                generate_env $backend $no_clients $no_replicas $batch_size > env
 
-                log Run no. $run_no: Benchmarking with params: r=$no_replicas b=$batch_size c=$no_clients
-
-                # generate remote configs
                 for i in `seq 1 4`; do
                     cop=cop0${i}
-                    log Generating configs 'for' $cop
-                    sudo -u tcarvalho ssh $cop \
-                        "cd tg/ycsb; mkdir -p config; cp auxiliary/generate config; cd config; ./generate $no_clients $no_replicas $batch_size"
+                    log Generating remote environment file 'for' $cop
+                    generate_env $backend $no_clients $no_replicas $batch_size | cmd $cop 'cat > tg/microbenchmarks/env'
+                done
+
+                # rebuild software
+                for i in `seq 1 4`; do
+                    cop=cop0${i}
+                    cmd $cop '. .cargo/env; cd tg; git pull; cd microbenchmarks; ./run compile'
                     if [ $? -ne 0 ]; then
-                        log Error: "Couldn't generatte configs for $cop"
+                        log Error: "Compile error in $cop"
                         exit 1
                     fi
                 done
 
-                # start replicas in cop0?
-                for i in `seq 0 $(expr $no_replicas - 1)`; do
-                    ippart=$(expr $i % 4)
-                    cop=cop0$(expr $ippart + 1)
-                    ip=192.168.70.$(expr 16 + $ippart)
+                # wait for systems to recover
+                bigcooldown
 
-                    log Starting replica id=$i 'in' $cop "($ip)"
-                    sudo -u tcarvalho ssh $cop \
-                        "cd tg/ycsb/service; sudo env ID=$i ./run" \
-                        >${targetdir}/replica_${i}_stdout 2>${targetdir}/replica_${i}_stderr &
-                    if [ $? -ne 0 ]; then
-                        log Error: "Couldn't start replica $i in $cop"
-                        exit 1
+                # run each test 3 times
+                for run_no in `seq 0 2`; do
+                    log Init of run no. $run_no
+
+                    targetdir="${RESULTS}/backend=${backend}/r=${no_replicas}/b=${batch_size}/c=${no_clients}/run=${run_no}"
+                    start=${targetdir}/start
+                    end=${targetdir}/end
+
+                    mkdir -p $targetdir
+                    date +%s > $start
+
+                    log Run no. $run_no: Benchmarking with params: backend=$backend r=$no_replicas b=$batch_size c=$no_clients
+
+                    # start replicas in cop0?
+                    for i in `seq 0 $(expr $no_replicas - 1)`; do
+                        ippart=$(expr $i % 4)
+                        cop=cop0$(expr $ippart + 1)
+                        ip=192.168.70.$(expr 16 + $ippart)
+
+                        log Starting replica id=$i 'in' $cop "($ip)"
+                        cmd $cop "cd tg/microbenchmarks; sudo env ID=$i ./run servers" \
+                            >${targetdir}/replica_${i}_stdout 2>${targetdir}/replica_${i}_stderr &
+                        if [ $? -ne 0 ]; then
+                            log Error: "Couldn't start replica $i in $cop"
+                            exit 1
+                        fi
+
+                        smallcooldown
+                    done
+
+                    # start clients in cop-gpu
+                    log Starting clients
+                    ./run clients >${targetdir}/client_stdout 2>${targetdir}/client_stderr
+
+                    if [ $? -eq 0 ]; then
+                        log Finished run $run_no
+                    else
+                        log Error: "Client exited with an error, check its stderr; skipping to next test case"
                     fi
-
-                    smallcooldown
-                done
-
-                # copy config generator
-                log Generating local configs
-                mkdir -p config
-                cp auxiliary/generate config
-
-                # run ycsb client
-                log Starting YCSB client
-                ./run $no_clients $no_replicas $batch_size \
-                    >${targetdir}/client_stdout 2>${targetdir}/client_stderr
-                if [ $? -ne 0 ]; then
-                    log Error: "YCSB client exited with an error, check its stderr; skipping to next test case"
+                    date +%s > $end
 
                     # kill replicas
                     for i in `seq 1 4`; do
                         cop=cop0${i}
                         log Killing all replicas 'in' $cop
-                        sudo -u tcarvalho ssh $cop "pkill -f service" >/dev/null 2>/dev/null &
+                        cmd $cop "cd tg/microbenchmarks; sudo ./run stop" >/dev/null 2>/dev/null &
                     done
+
                     bigcooldown
-                    date +%s > $end
-
-                    continue
-                fi
-
-                # kill replicas
-                for i in `seq 1 4`; do
-                    cop=cop0${i}
-                    log Killing all replicas 'in' $cop
-                    sudo -u tcarvalho ssh $cop "pkill -f service" >/dev/null 2>/dev/null &
                 done
-                bigcooldown
 
-                log Finished run $run_no successfully
-                date +%s > $end
+                log Finished benchmarking $no_clients clients
             done
 
-            log Finished benchmarking $no_clients clients
+            log Finished benchmarking a batch size of $batch_size
         done
 
-        log Finished benchmarking a batch size of $batch_size
+        log Finished benchmarking $no_replicas replicas
     done
 
-    log Finished benchmarking $no_replicas replicas
+    log Finished benchmarking backend $backend
 done
 
-log All tests finished successfully
+log All tests have finished executing
