retry test after failure

diff --git a/microbenchmarks/benchmark b/microbenchmarks/benchmark
--- a/microbenchmarks/benchmark
+++ b/microbenchmarks/benchmark
@@ -172,54 +172,58 @@ for backend in java rust; do
                     start=${targetdir}/start
                     end=${targetdir}/end
 
-                    mkdir -p $targetdir
-                    date +%s > $start
+                    while true; do
+                        error=0
 
-                    log Run no. $run_no: Benchmarking with params: backend=$backend r=$no_replicas b=$batch_size c=$no_clients
+                        rm -rf $targetdir
+                        mkdir -p $targetdir
+                        date +%s > $start
 
-                    # start replicas in cop0?
-                    for i in `seq 0 $(expr $no_replicas - 1)`; do
-                        ippart=$(expr $i % 4)
-                        cop=cop0$(expr $ippart + 1)
-                        ip=192.168.70.$(expr 16 + $ippart)
+                        log Run no. $run_no: Benchmarking with params: backend=$backend r=$no_replicas b=$batch_size c=$no_clients
 
-                        log Starting replica id=$i 'in' $cop "($ip)"
-                        cmd $cop "cd tg/microbenchmarks; sudo env ID=$i ./run servers" \
-                            >${targetdir}/replica_${i}_stdout 2>${targetdir}/replica_${i}_stderr &
-                        if [ $? -ne 0 ]; then
-                            log Error: "Couldn't start replica $i in $cop"
-                            exit 1
+                        # start replicas in cop0?
+                        for i in `seq 0 $(expr $no_replicas - 1)`; do
+                            ippart=$(expr $i % 4)
+                            cop=cop0$(expr $ippart + 1)
+                            ip=192.168.70.$(expr 16 + $ippart)
+
+                            log Starting replica id=$i 'in' $cop "($ip)"
+                            cmd $cop "cd tg/microbenchmarks; sudo env ID=$i ./run servers" \
+                                >${targetdir}/replica_${i}_stdout 2>${targetdir}/replica_${i}_stderr &
+                            if [ $? -ne 0 ]; then
+                                log Error: "Couldn't start replica $i in $cop"
+                                exit 1
+                            fi
+
+                            smallcooldown
+                        done
+                        mediumcooldown
+
+                        # start clients in cop-gpu
+                        log "Executing clients; check ${targetdir} for more details"
+                        sudo timeout 60m ./run clients >${targetdir}/clients_stdout 2>${targetdir}/clients_stderr
+
+                        if [ $? -eq 0 ]; then
+                            # move clients' latency file to target directory
+                            mv ${backend}/latencies* ${targetdir}/
+
+                            log Finished run $run_no
+                        else
+                            error=1
+                            log Error: "Clients exited with an error, check their stderr; retrying"
                         fi
+                        date +%s > $end
 
-                        smallcooldown
+                        # kill replicas
+                        for i in `seq 1 4`; do
+                            cop=cop0${i}
+                            log Killing all replicas 'in' $cop
+                            cmd $cop "cd tg/microbenchmarks; sudo ./run stop" >/dev/null 2>/dev/null &
+                        done
+
+                        bigcooldown
+                        [ $error -eq 0 ] && break || continue
                     done
-                    mediumcooldown
-
-                    # start clients in cop-gpu
-                    log "Executing clients; check ${targetdir} for more details"
-                    sudo timeout 90m ./run clients >${targetdir}/clients_stdout 2>${targetdir}/clients_stderr
-
-                    if [ $? -eq 0 ]; then
-                        # move clients' latency file to target directory
-                        mv ${backend}/latencies* ${targetdir}/
-
-                        log Finished run $run_no
-                    else
-                        # signal this run was unsuccessful
-                        touch ${targetdir}/error
-
-                        log Error: "Clients exited with an error, check their stderr; skipping to next test case"
-                    fi
-                    date +%s > $end
-
-                    # kill replicas
-                    for i in `seq 1 4`; do
-                        cop=cop0${i}
-                        log Killing all replicas 'in' $cop
-                        cmd $cop "cd tg/microbenchmarks; sudo ./run stop" >/dev/null 2>/dev/null &
-                    done
-
-                    bigcooldown
                 done
 
                 log Finished benchmarking $no_clients clients
