test

diff --git a/ycsb/auxiliary/orchestrate b/ycsb/auxiliary/orchestrate
--- a/ycsb/auxiliary/orchestrate
+++ b/ycsb/auxiliary/orchestrate
@@ -22,21 +22,30 @@ bigcooldown() {
 REPLICAS="4 7 10 13"
 BATCHES="8 16 32 128 512 1024"
 CLIENTS="1 10 30 60 100 1000"
+RESULTS=results
+
+# update cwd
+cd "../$(dirname $0)"
+ls
+exit 0
 
 # rebuild rust service in each cop node
 for i in `seq 1 4`; do
     cop=cop0${i}
     ssh $cop '. .cargo/env; cd tg; git pull; cd ycsb/service; env RUSTFLAGS="-C target-cpu=native" cargo build --release'
+    if [ $? -ne 0 ]; then
+        log Error: "Couldn't update service in $cop"
+        exit 1
+    fi
 done
-exit 0
 bigcooldown
 
 # execute benchmarks
-mkdir -p results
+mkdir -p $RESULTS
 for no_replicas in $(echo $REPLICAS); do
     for batch_size in $(echo $BATCHES); do
         for no_clients in $(echo $CLIENTS); do
-            targetdir="results/r=${no_replicas}/b=${batch_size}/c=${no_clients}"
+            targetdir="${RESULTS}/r=${no_replicas}/b=${batch_size}/c=${no_clients}"
             start=${targetdir}/start
             end=${targetdir}/end
 
@@ -53,7 +62,7 @@ for no_replicas in $(echo $REPLICAS); do
                     cop=cop0$(expr $ippart + 1)
                     ip=192.168.70.$(expr 16 + $ippart)
 
-                    log '>' Starting replica id=$i 'in' $cop "($ip)"
+                    log Starting replica id=$i 'in' $cop "($ip)"
 
                     #ssh $cop "cd tg; "
                 done
